# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hunter_msgs/HunterStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hunter_msgs.msg
import std_msgs.msg

class HunterStatus(genpy.Message):
  _md5sum = "ca557f5b13e1dbb8e7caa7cc072ca03c"
  _type = "hunter_msgs/HunterStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

int8 MOTOR_ID_FRONT = 0
int8 MOTOR_ID_REAR_LEFT = 1
int8 MOTOR_ID_REAR_RIGHT = 2

# motion state
float64 linear_velocity
float64 steering_angle

# base state
uint8 base_state
uint8 control_mode
uint16 fault_code
float64 battery_voltage
uint8 park_mode

# motor state
HunterMotorState[3] motor_states
# driver state
HunterDriverState[3] driver_states

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: hunter_msgs/HunterMotorState
float64 current
float64 rpm
float64 temperature
float64 motor_pose

================================================================================
MSG: hunter_msgs/HunterDriverState
float64 driver_voltage
float64 driver_temperature
uint8   driver_state
"""
  # Pseudo-constants
  MOTOR_ID_FRONT = 0
  MOTOR_ID_REAR_LEFT = 1
  MOTOR_ID_REAR_RIGHT = 2

  __slots__ = ['header','linear_velocity','steering_angle','base_state','control_mode','fault_code','battery_voltage','park_mode','motor_states','driver_states']
  _slot_types = ['std_msgs/Header','float64','float64','uint8','uint8','uint16','float64','uint8','hunter_msgs/HunterMotorState[3]','hunter_msgs/HunterDriverState[3]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,linear_velocity,steering_angle,base_state,control_mode,fault_code,battery_voltage,park_mode,motor_states,driver_states

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HunterStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.linear_velocity is None:
        self.linear_velocity = 0.
      if self.steering_angle is None:
        self.steering_angle = 0.
      if self.base_state is None:
        self.base_state = 0
      if self.control_mode is None:
        self.control_mode = 0
      if self.fault_code is None:
        self.fault_code = 0
      if self.battery_voltage is None:
        self.battery_voltage = 0.
      if self.park_mode is None:
        self.park_mode = 0
      if self.motor_states is None:
        self.motor_states = [hunter_msgs.msg.HunterMotorState() for _ in range(3)]
      if self.driver_states is None:
        self.driver_states = [hunter_msgs.msg.HunterDriverState() for _ in range(3)]
    else:
      self.header = std_msgs.msg.Header()
      self.linear_velocity = 0.
      self.steering_angle = 0.
      self.base_state = 0
      self.control_mode = 0
      self.fault_code = 0
      self.battery_voltage = 0.
      self.park_mode = 0
      self.motor_states = [hunter_msgs.msg.HunterMotorState() for _ in range(3)]
      self.driver_states = [hunter_msgs.msg.HunterDriverState() for _ in range(3)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2d2BHdB().pack(_x.linear_velocity, _x.steering_angle, _x.base_state, _x.control_mode, _x.fault_code, _x.battery_voltage, _x.park_mode))
      if len(self.motor_states) != 3:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (3, len(self.motor_states), 'self.motor_states')))
      for val1 in self.motor_states:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.current, _x.rpm, _x.temperature, _x.motor_pose))
      if len(self.driver_states) != 3:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (3, len(self.driver_states), 'self.driver_states')))
      for val1 in self.driver_states:
        _x = val1
        buff.write(_get_struct_2dB().pack(_x.driver_voltage, _x.driver_temperature, _x.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.motor_states is None:
        self.motor_states = None
      if self.driver_states is None:
        self.driver_states = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.linear_velocity, _x.steering_angle, _x.base_state, _x.control_mode, _x.fault_code, _x.battery_voltage, _x.park_mode,) = _get_struct_2d2BHdB().unpack(str[start:end])
      self.motor_states = []
      for i in range(0, 3):
        val1 = hunter_msgs.msg.HunterMotorState()
        _x = val1
        start = end
        end += 32
        (_x.current, _x.rpm, _x.temperature, _x.motor_pose,) = _get_struct_4d().unpack(str[start:end])
        self.motor_states.append(val1)
      self.driver_states = []
      for i in range(0, 3):
        val1 = hunter_msgs.msg.HunterDriverState()
        _x = val1
        start = end
        end += 17
        (_x.driver_voltage, _x.driver_temperature, _x.driver_state,) = _get_struct_2dB().unpack(str[start:end])
        self.driver_states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2d2BHdB().pack(_x.linear_velocity, _x.steering_angle, _x.base_state, _x.control_mode, _x.fault_code, _x.battery_voltage, _x.park_mode))
      if len(self.motor_states) != 3:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (3, len(self.motor_states), 'self.motor_states')))
      for val1 in self.motor_states:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.current, _x.rpm, _x.temperature, _x.motor_pose))
      if len(self.driver_states) != 3:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (3, len(self.driver_states), 'self.driver_states')))
      for val1 in self.driver_states:
        _x = val1
        buff.write(_get_struct_2dB().pack(_x.driver_voltage, _x.driver_temperature, _x.driver_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.motor_states is None:
        self.motor_states = None
      if self.driver_states is None:
        self.driver_states = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 29
      (_x.linear_velocity, _x.steering_angle, _x.base_state, _x.control_mode, _x.fault_code, _x.battery_voltage, _x.park_mode,) = _get_struct_2d2BHdB().unpack(str[start:end])
      self.motor_states = []
      for i in range(0, 3):
        val1 = hunter_msgs.msg.HunterMotorState()
        _x = val1
        start = end
        end += 32
        (_x.current, _x.rpm, _x.temperature, _x.motor_pose,) = _get_struct_4d().unpack(str[start:end])
        self.motor_states.append(val1)
      self.driver_states = []
      for i in range(0, 3):
        val1 = hunter_msgs.msg.HunterDriverState()
        _x = val1
        start = end
        end += 17
        (_x.driver_voltage, _x.driver_temperature, _x.driver_state,) = _get_struct_2dB().unpack(str[start:end])
        self.driver_states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d2BHdB = None
def _get_struct_2d2BHdB():
    global _struct_2d2BHdB
    if _struct_2d2BHdB is None:
        _struct_2d2BHdB = struct.Struct("<2d2BHdB")
    return _struct_2d2BHdB
_struct_2dB = None
def _get_struct_2dB():
    global _struct_2dB
    if _struct_2dB is None:
        _struct_2dB = struct.Struct("<2dB")
    return _struct_2dB
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
