!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  combination_method: 1
  enabled: true
  footprint_clearing_enabled: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      combination_method: 1
      enabled: true
      footprint_clearing_enabled: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      max_obstacle_height: 0.4
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
  max_obstacle_height: 0.4
state: []
